export const mysteriousFriend = `
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXx;...                                                                                         .;0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNx,...                                                                                             ;0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKc..... .                                                                                           .:KWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWM0;.........                                                                                           .lXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXc........                                                                                              .oNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWd......                                                                                                  .dNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0,......                                                                                                   .xNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNl.......                                                                                                    .dNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNd....... .                                                                                                    .dNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk'.....  ...                                                                                                    .xNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWO,......  .                                                                                                       'kWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0;......                                                                                                            ,OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0;.......                                                                                                             :KWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0;.......                                                                                                              .cXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0;.....                                                                                                                  .lXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWM0;....                                                                                                                     .lXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWK:...                                                                                                                        .oNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWK:.....                                                                                                 ..                     .dNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWO;......                                                                                             .......                     .xNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk,..... .                                                                                         ...........                      'OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNx'....                        ......... ............ .                                             ......                            ;0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNd.....                       ..                 ...                                                                                   .:KWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXl..  ..                                                                                ....                                             .lNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMXl...  .                 .                                                                                         ..                      .dNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXc..                     ..               .....                                .                 ........          ...                       'kWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXc.                       ..            ..';ccc;;,..                    ...     ..              ..',;:c::;'.         .'.                       ,0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXc.  .                     ...          .,:clodool:;;'.                  ...........           ..':clloolc:;,.         ..                        :KWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXc.                         ...        .,::loxO0Odolc:,.                  ............         ..;lx0KKKOocc:,.         ..                        .cXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXl.                         ...         ';:codONWNOdol:,'.            ................          .':od0NMW0dooc,.         ...                        .oNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXl.                          ....        .,;:lodO0Okdoo:;'          ....... .....''''''..        .,:lodk0kolclc;.         ...                         .xWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKc.                          ......       ..',:loddddlc::'.         ........ ...';:,;ll:;'.        .,:looollc:::,.         ...                          ,0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWK:                            ......         ..,:cllc:;;'.         ...','...'....,::,.clcc:;.        .,;;:::;;;,..          ...                           cXMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWO,                            .','''..           ........          ...,;,',;;;,''...cl';docc:;,..       ........            ..,'.                          .dWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk'                             .',,'...                             ..;::::llccl;.   'c:;oo:::;:c:,'..                      .;lc;.                           .kWWWWWWWWWWWWWWWWWWWWWWWWWMWWWNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk'                              ..'''''''.                   ........,:::cloxoll;  .   .,;;llccccllcc:,'..                  .,locc,                            ;KWWWWWWWWWWWWWWWWWWWWWWWMWNNNNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWx.                               ..'',;;;:;'................'''..',',,,,:ldxool:.  .,.  .:;';loolllollllcc:,'.....      ....,::cccll.                            lNWWWWWWWWWWWWWWWWWWWWWNNNNWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNd.                                .,,;:cc:,;;,,,,,,,,,,;;;,''',,,,,;::cldxxxoloc.   :c   .',,:ldxdooddooddddddlc;,;;,''',:::clllodool.                            .kWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNo.                                  .,cccll:;:cclllc::;::cccc::ccll:lodk0000xool'    ::     .':ocokxoddodkOkxkkkkxxkkdddoooddxxxkkOOOd'                             ,0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXl.                                 ...:cclooooooodddddolloododdddddxxkO0KXXX0dx:      ,:.    .;,cc:odkOOOO0K000K00KKKKKK000KK0OkO0KK0xlc'                             cXWWWWWWWWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXc.                                  ;c;clllcldxxxxxxxxxxxxxxxkkkkO00KXXXXNNNXkkd.      :d,    .;,':dxONNNNNNNWWNNNNNNNNNNXXNNX0O0XXXKOodOc                             .xWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0:.                                   .oxdoc::::::cc::;;lxxkO0KXKKXXNNNWWWWWWN000,       ,kk;    ..,xXKXNWWNWWWWWWWNWWWWWWWWWNXXXNWWWXKkxKO'                              ,KMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNXNWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0,                      ..             .,d0XOOkdkOkxxxxxxddddO0OO00KNWNNNNNNWWNKKo.      .o00d.    .cokKNNNNNWWWWWX0XXKKKXXNXXNNWWWNKO0OO0x'                                lNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNNWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWO,.                      ...               .;cccoddoodoc:,,:cokkxxOxdO00KNWNXKXWWXc       ;kXNx;.  ,cddkNNXX00NWNXKKNNNNNNNWWWWWWXXXK00K0x;.                                 .kWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWO,.                      ....                       ..,;'.       .,loox000KKXWNNWWWkc,'..,ok0NW0kkdokkxxKMWKkk0XKK0KK00OxccoxOKNNXKXXXKOo,                                     ,0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk'                          .. .      .                 .'..         .,cdKWNX0OKNWWWNXkocl0NWWWWWNKK0OOxkNNOxKWXKNNX0OKOc.  .,';lokOOxl;.                                        :KWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk'                           ..       .                   .,,.          ;xOXNWWXkONWWNNXK0XWWWWWWWWWWNXXNWXkkXWXKXNXKKKx'    .;:;,...','..                                         :KWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNd.                               ..    .                    ,:'           :x0NNNWNK0XWWWWWMWWWWNWWWWWWWMWNNOOWWXXXNNXXXk'     .;c:'  .....         ..                                ;0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNo.                               ...     .                   .,;.          .xOKWXXWWNKNWWWMWWWWWNXWMWWWWNXWXOO00KNNWNNX0l      'cc,.    ..          ..                                 ,OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNd.                                            ..               .cc.         .l0kXWNNWWNXNWWWWWWWWNXNMWWNXNWWXXNXNNNWWNN0x;      ,dx:.                ;:                                  .dNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWd.                                             ,:.              .lOl.         .xddXNkxKNNXXX000KWWNNWWMNKXWWWNKOx0WWNXXNOkc     .:xkl.                'l.                                  .cKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXl.                                              .:.               ;K0,         ,lcl0k. ;kX0O0KXXKNW0OXWWOlkNWWK0K0OKNKKOxdkc     .d0Oo.                 c:                                    ;OWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNk;                                                .,.               .dKc        .odk0kl.  .lOOKMWWNXXXN0Kk' 'xNNXNMNxdOKXdxxl:.    'ONNx.                 .,.                                    'dXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKl.                                                 .;.                :Oc.        ;:oXk'    .'cKMMWWOoOWKl.   :0NWWWx',xNOcod0O.    '0NNo                   '.                                     .:0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNk;.                                                  .:.                'kk.        ..'OO.      .xWWWXx,cKWk.   .oNWM0,.xNWd...lc.    '0NXl                   ..                                       'kWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0c..                                                   .:.                .dK;          .ok.       ;xKNx,  ;Od.    'OWXc .okO:          ,KN0:                   ..                                        .oXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNx,.                                                     ';.                 ;0l           'c.       .'ok;.  ...      'c;.   .o,          :XNK:                   .,                                         .cKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW0:.                                                       ..                  .dd.          'c.         ';                    .l,          cXN0:                   .;.                                         .,kWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXo.    ..                                                                        l0;          .;.         ,:.                   .l;         .cXX0:                   .;.                                           .lXWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWO;.                                                                               :Ko.         .;.         'c.                   .o:         .lNWXc                   .:'                                            .;kNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWXd.                                                           .'                    ;00:         .;.         .o,                   .od.        ;kXNK:                   .:,                                              .cKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWK:.                                                            ''                    .kKx,        .;.         .o;               ..  .dNKo.   ..cOKk0Xc                    ',                                                ,kNWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNk'                                                             .'.                    .:k0k:.     .xx,..       .o:              'OKl..kWW0' .'lkKKO0NO'                    .,.                                                .lKWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKc.                                                                                      ;k00Od;.    :0old.      .l:         .,;. lNMO.'OWWO:,c0Kxdx0N0;                      ..                                                  ,kNWWMWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWk,                                                                                        :xkKK00xl,..c0Kdx:     .cKo.       .xNWd.lNWkcxXNX0O00Kkc:d0x.                     ...                                                    .c0WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWMXo.                                                                                          ,xOxxKWWOlxk0K0XKc,. ..oNXd:.    .ckKK0kx0XKXWW0x0kd0Odkxl;.                                                                               'kWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWO;.                                                                                            ;kkxk0Kxxll0KKWWWNk..;o00XN0,  'kXXKKNWXOOKWWWXXX0OOkdxl.                                                                                  .lKWWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWKl.                                                                                              .c0OkkxooxkkONWWWWWxoOKNXNWWk.,OKKWWWWWWX0XWWWWN0kkOk:.                                                                                      ,OWWWWWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWNk,                                                                                                  ;xkkxdloOXKO0NWMWNNWWWWWWWN0KXXWMWWWWWWWMWWWWXOOk:.                                                                                         .dXWWWMWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWWWXl.                                                                                                    .;:ldo::kNNO0WMWNNWWWWWWWWMWNWWMWWWWMWWWWNOxxxd'                                                                                            .:0WWWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWW0;.                                                                                                        .'cc;lOWXk0WWWWWWWWWWWWWWWWWWWWWWWWNKkkxod:.                                                                                               .dXWWWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWWWx'..                                                                                                          .,oxkKXxxXNXNNNNNNNNNNWWWWNXNNNNKkxdclo:.                                                                                                 .:0WWWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWWWXo...                                                                                                             ,xKKKkdkkOkkkkOkk0OKXKKK0kOOkxocc;',.                                                                                                     .dNWWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWWW0:.                                                                                                                 .;odxl:::loocc:;;::::cc;,;;,,,.....                                                                                                       .cKWWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWWWNd.                                                                                                                       ...'.',,,'''.'''.'',''',,,.                                                                                                             ,OWWWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWWW0:.                                                                                                                            ..'',,,,,,;;;,,,,,''...                                                                                                              .dNWWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWWNx'.                                                                                                                              ...',,''''''......'...                                                                                                               .cKWWWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWWWKc.                                                                                                                                ......................                                                                                                                 ;0WWWWWWWWWWWWWW
WWWWWWWWWWWWWWWWNk,                                                                                                                                  ..............          ..'.                                                                                                            ;KWWWWWWWWWWWWW
WWWWWWWWWWWWWWWKl.                                                                                                                              .        .........  ............                                                                                                             .oWWWWWWWWWWWWW
WWWWWWWWWWWWWNk,..                                                                                                  .                              ......................''...                                                                                                                :XMWWWWWWWWWWW
WWWWWWWWWWWWXl.                                         ...                                                         ....                           .......'oO00000Okddddl;;,.                                                                                                                 .;ldk0XNWWWWWW
WWWWWWWWWWWO;.                                       ......                                                          ....                           .....;OWWWWWWWWWMMWWXd,.                                                                                                                       ..,:ldOKN
WWWWWWWWWNx.                                       ........                                                          .....                            ...oXWWWWWWWWWWWWWKc.                                                                                                                               .'
WWWWWWWWNd.                                       .......                                                             ...'..                           .'oXMWWWWWWWWWWWWO'                                                                                                                                  
WWWWWWWM0'                                      .......                        ..                                      ...''.                           'l0NWWWNNXKKKOdo:.  ..'''''....                                    .                                                                                
WWWWWWWNl.                                    ........  ..                    ...                                       . .''.                 .........'',lxddollcllllc;,,;c:,'....',;,.                                 ...                                                                               
WWWWWXOc.                                   ..........  .                     ... .                                   .    .''.             .','.   .;cclodxkO000KKXNWWWKO0OOx'       .,,.                                ...                                                                               
WNKxc'.                                    ...........                       .....'.                                  ..    .''.          .;c:.    .:lokKNWWWWMWWWWWWWWWWWWX0l.       .:o:.                    ......     ....                                                                              
d:..                                     .............        .     .      ......'....                                ...    .,'.        ,ccc'     .okO0XNWWWWWWWWWWWWWWWWNO:.         cK0,                    ......     ....                                                                              
...                                     .............       ..    ..       ............                                ..     .,'.       ,clo,      .:odxKWWWWWWWWWWWWWWNNK;           ;KX:                .  .......     ....    .                                                                         
                                      ..............       ...   ..      .................                              ..    .','       .:xKo         .l0WWWWWWWWWWWWWWNKd.          .oKklc;.           ...  .......     .....  ...                                                                        
                                      ..............     ....   ...       ...................                            .'.    .,,..      ;KMK,        .oOXWWNNWWWWWWNNX0l,.  ...,;:ldOKXXNO'            ...  ..... .   .......  ..'.                                                                       
`;